version: '3'

tasks:
  default:
    cmds:
      - task: install
      - task: run
  dev:
    cmds:
      - task: install_dev
      - task: install
      - task: run_dev
  install:
    cmds:
      - pip install -r requirements.txt
  install_dev:
    cmds:
      - pip install -r requirements_dev.txt
  run:
    cmds:
      - fastapi dev ./src/HiveBox/main.py
  run_dev:
    cmds:
      - fastapi dev ./src/HiveBox/main.py --reload
  precommit:
    cmds:
      - pre-commit run --all-files
  compose:
    cmds:
      - docker compose up -d --build --remove-orphans
