version: '3'

tasks:
  default:
    cmds:
      - task: sync
      - task: run
  dev:
    cmds:
      - task: sync
      - task: test
      - task: lint
      - task: run_dev
  sync:
    cmds:
      - uv sync
  test:
    cmds:
      - uv run pytest
  lint:
    cmds:
      - hadolint Dockerfile
      - uv run pylint src/hive_box
      - uv run ruff check
      - uv run ruff format
  run:
    cmds:
      - uv run fastapi dev ./src/hive_box/main.py
  precommit:
    cmds:
      - uv run pre-commit run --all-files
  compose:
    cmds:
      - docker compose up -d --build --remove-orphans
