name: Hadolint

on: [push]

jobs:
  lint_hadolint:
    runs-on: ubuntu-24.04
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
      with:
        egress-policy: audit

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf
      with:
        dockerfile: Dockerfile
