name: Pylint

on: [push]

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  lint_pylint:
    runs-on: ubuntu-24.04
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
      with:
        egress-policy: audit
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Set up Python 3.13
      uses: actions/setup-python@3542bca2639a428e1796aaa6a2ffef0c0f575566 # v3.1.4
      with:
        python-version: "3.13"
    - name: Install uv
      uses: astral-sh/setup-uv@6b9c6063abd6010835644d4c2e1bef4cf5cd0fca # v6.0.1
    - name: Install dependencies
      run: |
        uv sync --locked
    - name: Analysing the code with pylint
      run: |
        uv run pylint $(git ls-files '*.py')
