name: Hadolint

on: [push]

jobs:
  lint_hadolint:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf
      with:
        dockerfile: Dockerfile
